# Code Review Crew - Crew Configuration
# Efficient multi-agent configuration for code review

crew_config:
  name: "Code Review Crew"
  description: "Multi-agent code review crew with specialized expertise"
  process: "sequential"
  verbose: false
  memory: false
  cache: true
  max_rpm: 200
  language: "en"

  # Manager LLM configuration
  manager_llm:
    temperature: 0.1
    max_tokens: 1500
    timeout: 45

  # Planning disabled for speed
  planning: false

  # Performance optimization
  performance:
    parallel_execution: false
    max_concurrent_tasks: 3
    task_timeout: 60  # 1 minute per task

  # Output configuration
  output_dir: "output"

  # Multi-agent coordination
  coordination:
    enable_context_sharing: true
    agent_handoff_timeout: 20
    max_agent_iterations: 3